# Generated by Django 4.0.3 on 2022-05-07 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0026_alter_employe_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('add_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.employe')),
                ('add_contact_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_contacts', to='account.employe')),
            ],
        ),
    ]
