# Generated by Django 4.0.3 on 2022-03-19 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0008_rename_profile_employe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(blank=True)),
                ('starteddate', models.DateTimeField(blank=True)),
                ('upload', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('', ''), ('completed', 'completed'), ('not completed', 'not completed')], default=False, max_length=100)),
                ('name', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField()),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='task_images/')),
                ('checker', models.ManyToManyField(related_name='checkers', to='account.employe')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creators', to='account.employe')),
                ('employe', models.ManyToManyField(related_name='employes', to='account.employe')),
                ('section', models.ManyToManyField(to='account.section')),
            ],
        ),
    ]
