# Generated by Django 4.0.3 on 2022-03-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('completed', 'completed'), ('not completed', 'not completed')], default=False, max_length=100),
        ),
    ]
