# Generated by Django 4.0.3 on 2022-03-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_employe_gender'),
        ('task', '0002_alter_task_name_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='employe',
            field=models.ManyToManyField(blank=True, to='account.employe'),
        ),
    ]
