# Generated by Django 4.0.3 on 2022-03-25 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_email_alter_employe_author_alter_employe_position_and_more'),
        ('task', '0003_alter_task_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creators', to='account.employe'),
        ),
    ]
