# Generated by Django 4.0.3 on 2022-04-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='starteddate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('in progress', 'in progress'), ('completed', 'completed'), ('not completed', 'not completed')], default=False, max_length=100),
        ),
    ]
