# Generated by Django 4.0.3 on 2022-04-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_employe_user_alter_section_name'),
        ('task', '0006_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='employe',
            field=models.ManyToManyField(blank=True, null=True, to='account.employe'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('in progress', 'in progress'), ('completed', 'completed'), ('not completed', 'not completed')], default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='upload',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
