# Generated by Django 4.0.3 on 2022-04-20 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_employe_user_alter_section_name'),
        ('task', '0007_alter_task_description_alter_task_employe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creators', to='account.employe'),
        ),
        migrations.AlterField(
            model_name='task',
            name='employe',
            field=models.ManyToManyField(blank=True, to='account.employe'),
        ),
    ]
