# Generated by Django 4.0.3 on 2022-04-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_task_creator_alter_task_employe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='deadline',
            new_name='end',
        ),
    ]
