# Generated by Django 4.0.3 on 2022-04-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_rename_deadline_task_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
