# Generated by Django 4.0.3 on 2022-04-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_alter_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='starteddate',
            new_name='start',
        ),
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
