# Generated by Django 4.0.3 on 2022-04-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_rename_starteddate_task_start_alter_task_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
