# Generated by Django 4.0.3 on 2022-04-20 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_employe_user_alter_section_name'),
        ('task', '0013_alter_task_end_alter_task_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='employe',
        ),
        migrations.AddField(
            model_name='task',
            name='employe',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.PROTECT, to='account.employe'),
        ),
    ]
