# Generated by Django 4.0.3 on 2022-04-20 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_employe_user_alter_section_name'),
        ('task', '0018_remove_task_employe_task_employe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='section',
        ),
        migrations.AddField(
            model_name='task',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.section'),
        ),
    ]
