# Generated by Django 4.0.3 on 2022-05-03 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_user_has_profile_alter_user_slug'),
        ('task', '0019_remove_task_section_task_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.section'),
        ),
    ]
