# Generated by Django 4.0.3 on 2022-05-03 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_user_has_profile_alter_user_slug'),
        ('task', '0020_alter_task_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.section'),
        ),
    ]
