# Generated by Django 4.0.3 on 2022-05-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0023_alter_task_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='section',
        ),
    ]
