# Generated by Django 4.0.3 on 2022-05-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0025_alter_task_creator_alter_task_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
