# Generated by Django 4.0.3 on 2022-05-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0026_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
