# Generated by Django 4.0.3 on 2022-05-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0027_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
