# Generated by Django 3.2.13 on 2022-05-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0029_alter_task_end_alter_task_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='message',
        ),
    ]
