# Generated by Django 3.2.13 on 2022-05-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0030_rename_title_task_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='message',
            new_name='title',
        ),
    ]
