# Generated by Django 4.0.3 on 2022-03-18 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_section_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='account.section'),
        ),
    ]
