# Generated by Django 4.0.3 on 2022-03-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_adress_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sad',
            field=models.TextField(blank=True),
        ),
    ]
