# Generated by Django 4.0.3 on 2022-03-18 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_sad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sad',
        ),
    ]
