# Generated by Django 4.0.3 on 2022-03-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_profile_sad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Employe',
        ),
    ]
