# Generated by Django 4.0.3 on 2022-03-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_profile_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='gender',
            field=models.CharField(blank=True, choices=[('', ''), ('Male', 'Male'), ('Female', 'Female')], max_length=150, null=True),
        ),
    ]
