# Generated by Django 4.0.3 on 2022-03-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_employe_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='gender',
            field=models.CharField(blank=True, choices=[('Not specified', 'Not specified'), ('Male', 'Male'), ('Female', 'Female')], default='Not specified', max_length=150, null=True),
        ),
    ]
