# Generated by Django 4.0.3 on 2022-03-25 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_employe_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='employe',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.employe'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.postion'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.section'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postion',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='account.section'),
        ),
        migrations.AddField(
            model_name='employe',
            name='email_add',
            field=models.ManyToManyField(to='account.email'),
        ),
    ]
