# Generated by Django 4.0.3 on 2022-04-11 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_remove_postion_section_alter_employe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postion',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(choices=[('', ''), ('CEO', 'CEO'), ('Agent', 'Agent'), ('Call Center', 'Call Center')], default=False, max_length=250, null=True),
        ),
    ]
