# Generated by Django 4.0.3 on 2022-04-11 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_postion_author_alter_section_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.employe'),
        ),
    ]
