# Generated by Django 4.0.3 on 2022-04-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_employe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postion',
            name='position',
            field=models.CharField(choices=[('', ''), ('director', 'director'), ('deputy', 'deputy'), ('worker', 'worker')], default=False, max_length=250, null=True),
        ),
    ]
