# Generated by Django 4.0.3 on 2022-04-16 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_addusercount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(choices=[('', ''), ('CEO', 'CEO'), ('Agent', 'Agent'), ('Manager-dispatcher', 'Manager-dispatcher'), ('Accountant', 'Accountant'), ('Sales Manager', 'Sales Manager'), ('Office Manager', 'Office Manager')], default=False, max_length=250, null=True),
        ),
    ]
