# Generated by Django 4.0.3 on 2022-04-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_employe_user_alter_section_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
