# Generated by Django 4.0.3 on 2022-05-03 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_user_has_profile_alter_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_section', to='account.section'),
        ),
    ]
