# Generated by Django 4.0.3 on 2022-05-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_employe_last_login_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='country',
            field=models.CharField(blank=True, choices=[('Tashkent', 'Tashkent'), ('Samarkand', 'Samarkand'), ('Andijan', 'Andijan'), ('Karakalpakstan', 'Karakalpakstan'), ('Ferghana', 'Ferghana'), ('Bukhoro', 'Bukhoro'), ('Namangan', 'Namangan'), ('Khorezm', 'Khorezm'), ('Kashkadarya', 'Kashkadarya'), ('Jizzakh', 'Jizzakh'), ('Surkhandaryo', 'Surkhandaryo'), ('Navoi', 'Navoi')], max_length=120, null=True),
        ),
    ]
