# Generated by Django 4.0.3 on 2022-05-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_remove_employe_last_login_employe_updated_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='updated_on',
            new_name='last_echo',
        ),
        migrations.AddField(
            model_name='employe',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='status',
            field=models.CharField(choices=[('online', 'On-line'), ('offline', 'Off-line')], default='online', max_length=10),
        ),
    ]
