# Generated by Django 4.0.3 on 2022-05-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_rename_updated_on_employe_last_echo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='last_echo',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='user2',
        ),
        migrations.AddField(
            model_name='employe',
            name='connections',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='online',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
