# Generated by Django 4.0.3 on 2022-05-10 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_remove_employe_device_id_remove_employe_last_echo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='connections',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='online',
        ),
        migrations.AddField(
            model_name='employe',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='last_echo',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employe',
            name='user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employe',
            name='status',
            field=models.CharField(choices=[('online', 'On-line'), ('offline', 'Off-line')], default='online', max_length=10),
        ),
    ]
