# Generated by Django 4.0.3 on 2022-05-10 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_remove_employe_connections_remove_employe_online_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='last_echo',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_online',
        ),
        migrations.AddField(
            model_name='employe',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employe',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
