# Generated by Django 4.0.3 on 2022-05-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_remove_employe_device_id_remove_employe_last_echo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='last_login',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
