# Generated by Django 4.0.3 on 2022-05-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_remove_employe_last_login_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='employe',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
