# Generated by Django 4.0.3 on 2022-05-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_chatsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='is_online',
        ),
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
