# Generated by Django 4.0.3 on 2022-05-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_employe_andijan_employe_bukhoro_employe_ferghana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tashkent', models.PositiveIntegerField(blank=True, null=True)),
                ('Samarkand', models.PositiveIntegerField(blank=True, null=True)),
                ('Andijan', models.PositiveIntegerField(blank=True, null=True)),
                ('Karakalpakstan', models.PositiveIntegerField(blank=True, null=True)),
                ('Ferghana', models.PositiveIntegerField(blank=True, null=True)),
                ('Bukhoro', models.PositiveIntegerField(blank=True, null=True)),
                ('Namangan', models.PositiveIntegerField(blank=True, null=True)),
                ('Khorezm', models.PositiveIntegerField(blank=True, null=True)),
                ('Kashkadarya', models.PositiveIntegerField(blank=True, null=True)),
                ('Jizzakh', models.PositiveIntegerField(blank=True, null=True)),
                ('Surkhandaryo', models.PositiveIntegerField(blank=True, null=True)),
                ('Navoi', models.PositiveIntegerField(blank=True, null=True)),
                ('Sirdaryo', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employe',
            name='Andijan',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='Bukhoro',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='Ferghana',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='Jizzakh',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='Karakalpakstan',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='Kashkadarya',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='Khorezm',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='Namangan',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='Navoi',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='Samarkand',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='Sirdaryo',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='Surkhandaryo',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='Tashkent',
        ),
    ]
