# Generated by Django 4.0.3 on 2022-05-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_countrycount_remove_employe_andijan_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryCount',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
