# Generated by Django 4.0.3 on 2022-05-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_employe_date_alter_employe_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='country',
            field=models.CharField(blank=True, choices=[('Tashkent', 'Tashkent'), ('Samarkand', 'Samarkand'), ('Andijan', 'Andijan'), ('Nukus', 'Nukus'), ('Ferghana', 'Ferghana'), ('Bukhara', 'Bukhara'), ('Namangan', 'Namangan'), ('Urganch', 'Urganch'), ('Qarshi', 'Qarshi'), ('Jizzakh', 'Jizzakh'), ('Termiz', 'Termiz'), ('Navoiy', 'Navoiy'), ('Sirdaryo', 'Sirdaryo')], max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
