# Generated by Django 4.0.3 on 2022-05-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_chatsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('director', 'director'), ('deputy', 'deputy'), ('worker', 'worker')], max_length=35, null=True),
        ),
    ]
