# Generated by Django 4.0.3 on 2022-05-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0056_admin_deputy_director_worker_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
