# Generated by Django 3.2.13 on 2022-05-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0057_user_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='gender',
            field=models.CharField(blank=True, choices=[('Not specified', 'Not specified'), ('Male', 'Male'), ('Female', 'Female')], max_length=150, null=True),
        ),
    ]
