# Generated by Django 3.2.13 on 2022-05-20 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0062_alter_employe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.employe'),
        ),
    ]
