# Generated by Django 3.2.13 on 2022-05-22 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0063_alter_employe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_position', to='account.postion'),
        ),
    ]
