# Generated by Django 3.2.13 on 2022-05-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0064_alter_employe_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_email',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
