# Generated by Django 3.2.13 on 2022-05-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0065_user_password_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_email',
        ),
        migrations.AddField(
            model_name='employe',
            name='password_email',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
