# Generated by Django 3.2.13 on 2022-05-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0066_auto_20220524_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='email_add',
        ),
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
